### ISSUE TITLE
Language barrier

### ISSUE THREAD

**Issue by Brandon-Isaac** [MrAndiw/instagram-roasting#1]
- [x] Can you make it to support the English Language?

**Comment by MrAndiwArch** [comment]
for the roast ? 
you can change it on config.json here "TEXT_ROAST" to something like "Please Roast This Instagram Account Politely"

{
    "API_KEY_GEMINI" : "xxxxxxxxx",
    "TEXT_ROAST" : "Please Roast This Instagram Account Politely"
}
